### ISSUE TITLE
in takeover mode using code action auto import only works once

### ISSUE THREAD

**Issue by dukeofcool199** [yaegassy/coc-volar#112] opened 2022-01-31 19:50 UTC
When using volar in takeover mode (by following the instructions laid out in this projects readme), when i use the code action auto module import, it works only once before i have to restart the server.

I am met with this erro message

[coc.nvim] Error on applyEdits: {path to file} changed before apply edit.

after restarting the server on a .vue file, i am able to use the auto import from within a typescript only once yet again

for context this is a vue2 project, and i followed the instructions on the volar project readme for setting things up vue 2 support

**Comment by yaegassy** [comment] 2022-02-01 02:04
Hi, I have reproduced the issue. It also reproduces in a vue3 + ts project created with vite's vue-ts.

I've also tried using LSP clients other than coc-volar, but the same symptoms occur. It seems to be a problem on the Language Server side.

### DEMO (mp4) coc-volar

https://user-images.githubusercontent.com/188642/151902386-719d63cc-a275-419d-9cf4-5917c491614b.mp4

---

I also tried it with VSCode's volar extension. No error message seems to be displayed, but there seems to be a problem.

### DEMO (mp4) VSCode

https://user-images.githubusercontent.com/188642/151902492-3927416a-80a0-4d60-9e38-42dfe2dc79bf.mp4

**Comment by yaegassy** [comment] 2022-02-01 02:31
Workaround. Auto-import from auto-completion seems to be working correctly.

This may be fixed in a future update of upstearm, but until then, you may want to auto-import from auto-completion.

https://user-images.githubusercontent.com/188642/151904875-28d77a10-55e7-4933-a2af-44bc07ccb8a2.mp4

**Comment by johnsoncodehk** [comment] 2022-04-21 04:44
This problem maybe already fixed in v0.34.6, could you take a try?
https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#0346

**Comment by yaegassy** [comment] 2022-04-21 11:47
@johnsoncodehk Sorry for the delay in getting back to you. The take over mode seems to be broken in coc-volar at the moment and I was unable to get a correct confirmation.

Duplicate dagnostics for typescript file...

<img width="362" alt="demo" src="https://user-images.githubusercontent.com/188642/164451414-44115e1b-467a-444f-93c6-7edf4a9f2188.png">

Perhaps something is wrong around useSecondServer or langId changes... Of course, this is not a problem with VSCode's volar extension, but a bug in coc-volar.

**Comment by yaegassy** [comment] 2022-04-21 14:45
check: <https://github.com/johnsoncodehk/volar/commit/dc7f580c658961d84355c8f020ae23408295e4f2>

**Comment by yaegassy** [comment] 2022-04-21 15:13
@johnsoncodehk There were many other problems besides the duplicate diagnostics in Take Over Mode, but after updating to v0.34.9, the critical problem has been resolved.

Thanks for the adjustment.

However, the problem of duplicate diagnostics itself seems to continue. The auto import issue from CodeAction did not change the situation either.

**Comment by johnsoncodehk** [comment] 2022-04-21 15:18
> However, the problem of duplicate diagnostics itself seems to continue.

Hi @yaegassy, is it a regression of `@volar/vue-language-server`? Can you confirm in which version this problem started happening?

**Comment by yaegassy** [comment] 2022-04-21 15:32
Yes, from volar.

```
[Trace - 12:27:41 AM] Received request 'vue/docVersion - (1)'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts"
}


[Trace - 12:27:41 AM] Sending response 'vue/docVersion - (1)'. Processing request took 0ms
Result: 1


[Trace - 12:27:41 AM] Received request 'vue/docVersion - (2)'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts"
}


[Trace - 12:27:41 AM] Sending response 'vue/docVersion - (2)'. Processing request took 0ms
Result: 1


[Trace - 12:27:41 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        }
    ]
}


[Trace - 12:27:41 AM] Received request 'vue/docVersion - (3)'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts"
}


[Trace - 12:27:41 AM] Sending response 'vue/docVersion - (3)'. Processing request took 0ms
Result: 1


[Trace - 12:27:41 AM] Received request 'vue/docVersion - (4)'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts"
}


[Trace - 12:27:41 AM] Sending response 'vue/docVersion - (4)'. Processing request took 0ms
Result: 1


[Trace - 12:27:41 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        }
    ]
}


[Trace - 12:27:41 AM] Received request 'vue/docVersion - (5)'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts"
}


[Trace - 12:27:41 AM] Sending response 'vue/docVersion - (5)'. Processing request took 0ms
Result: 1


[Trace - 12:27:41 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        },
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        }
    ]
}


[Trace - 12:27:41 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/yaegassy/sandbox/check-volar-next/src/main.ts",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        },
        {
            "range": {
                "start": {
                    "line": 6,
                    "character": 0
                },
                "end": {
                    "line": 6,
                    "character": 5
                }
            },
            "severity": 1,
            "source": "ts",
            "code": 2304,
            "message": "Cannot find name 'dummy'."
        }
    ]
}
```

**Comment by yaegassy** [comment] 2022-04-21 15:40
@johnsoncodehk This seems to have occurred since `v0.34.1`. Since coc-volar did not support upgrades in v0.34.0, we have not checked v0.34.0.

**Comment by yaegassy** [comment] 2022-06-20 00:55
I reported the issue to coc.nvim.

**Closed** 2022-06-22 00:58 UTC
