### ISSUE TITLE
Language server does not recognize files that have been added or changed

### ISSUE THREAD

**Issue by chaozwn** [yaegassy/coc-volar#299] opened 2023-06-29 03:44 UTC
volar must work with watchman?

**Comment by yaegassy** [comment] 2023-06-29 03:58
Installation of watchman is recommended, not required. Check this section of the README.

- <https://github.com/yaegassy/coc-volar#recommended-additional-installation-of-watchman>

**Comment by chaozwn** [comment] 2023-06-29 06:46
> Installation of watchman is recommended, not required. Check this section of the README.
> 
> * https://github.com/yaegassy/coc-volar#recommended-additional-installation-of-watchman

but after `brew install watchman`, new add file also can't be identify by volar lsp. Restart server works well.

**Comment by yaegassy** [comment] 2023-06-29 07:16
You can check if watchman is working properly by

1. Execute `:CocCommand workspace.showOutput` command
2. Choose `watchman`

In this state, create a vue file or ts, etc file in your project and save the file. If there is a change on the watchman screen side, it is working correctly.

**Comment by chaozwn** [comment] 2023-06-29 11:33
> You can check if watchman is working properly by
> 
> 1. Execute `:CocCommand workspace.showOutput` command
> 2. Choose `watchman`
> 
> In this state, create a vue file or ts, etc file in your project and save the file. If there is a change on the watchman screen side, it is working correctly.

Although Watchman has logs, the notifications are still not functioning properly.

**Comment by chaozwn** [comment] 2023-06-29 11:37
> You can check if watchman is working properly by
> 
> 1. Execute `:CocCommand workspace.showOutput` command
> 2. Choose `watchman`
> 
> In this state, create a vue file or ts, etc file in your project and save the file. If there is a change on the watchman screen side, it is working correctly.

![image](https://github.com/yaegassy/coc-volar/assets/51357674/83b6c475-4114-46e3-8754-f8f309e42712)

**Comment by yaegassy** [comment] 2023-06-29 21:41
It seems to be working fine in my environment. I have tried the following steps. I am using the latest version of @yaegassy/coc-volar.

**DEMO(mp4)**

https://github.com/yaegassy/coc-volar/assets/188642/3d9ba5c8-703e-4c25-9b69-59f8f81b385f

---

1. Create a vue project using create-vue.

   **Prepare**:
 
   ```
   mkdir -p $HOME/check
   cd $HOME/check
   npm init vue@latest check-issue-299
 
   cd check-issue-299
   npm i
   ```

2. open src/App.vue.

3. Create a new FooBar component (`components/FooBar.vue`).

4. Try to import FooBar component in App.vue.

**Comment by chaozwn** [comment] 2023-06-30 03:17
> 

sorry, i test through copy older files.if you copy components/FooBar.vue to components/FooBar2.vue. Work normal?
By the way, have you configured your watchman to ignore node_modules? Can you show me your commonly used .watchmanconfig?

**Comment by chaozwn** [comment] 2023-06-30 03:18
> It seems to be working fine in my environment. I have tried the following steps. I am using the latest version of @yaegassy/coc-volar.
> 
> **DEMO(mp4)**
> 
>  coc-volar-issue-299-1.mp4 
> 1. Create a vue project using create-vue.
>    ```
>    mkdir -p $HOME/check
>    cd $HOME/check
>    npm init vue@latest check-issue-299
>    
>    cd check-issue-299
>    npm i
>    ```
> 2. open src/App.vue.
> 3. Create a new FooBar component (`components/FooBar.vue`).
> 4. Try to import FooBar component in App.vue.

in this way, i work normal.

**Comment by yaegassy** [comment] 2023-06-30 03:31
There are no settings regarding the watchman. In my environment, if I copy a component, of course it will reflect that as well.

**Comment by chaozwn** [comment] 2023-06-30 03:39
> There are no settings regarding the watchman. In my environment, if I copy a component, of course it will reflect that as well.
Can you please paste your dot configuration?

**Comment by yaegassy** [comment] 2023-06-30 03:42
By the way, I will also tell you how to check the logs at the language server level.

When coc.nvim detects changes in watchman, it sends the files to the language server with the LSP method `workspace/didChangeWatchedFiles`.

> In coc-settings.json, set "vue-semantic-server.trace.server": "verbose"

https://github.com/yaegassy/coc-volar/assets/188642/35d69426-a23a-44d3-9b26-51df377998dc

**Comment by chaozwn** [comment] 2023-06-30 04:17
> By the way, I will also tell you how to check the logs at the language server level.
> 
> When coc.nvim detects changes in watchman, it sends the files to the language server with the LSP method `workspace/didChangeWatchedFiles`.
> 
> > In coc-settings.json, set "vue-semantic-server.trace.server": "verbose"
> 
>  coc-volar-issue-299-2.mp4
In fact, it only works the first time, and afterwards, when I add files again, it can't recognize them.
<img width="1649" alt="image" src="https://github.com/yaegassy/coc-volar/assets/51357674/e64aa497-c78e-48c4-8c91-ea6ad02d45ab">
<img width="1551" alt="image" src="https://github.com/yaegassy/coc-volar/assets/51357674/5629e589-c035-4810-a485-6e88c6dd9fc6">

**Comment by chaozwn** [comment] 2023-06-30 04:19
i copy demo2.vue, it works well. but when create demo3.vue, demo4.vue. it's bad.

**Comment by yaegassy** [comment] 2023-06-30 04:36
It may be a problem with the language server itself. Please check the issue on the language server itself or report the issue. If possible, it would be easier for maintainers to understand the problem if they can reproduce it in VSCode.

**Comment by yaegassy** [comment] 2023-06-30 04:39
Changed the title of the issue.

**Comment by chaozwn** [comment] 2023-06-30 05:11
> It may be a problem with the language server itself. Please check the issue on the language server itself or report the issue. If possible, it would be easier for maintainers to understand the problem if they can reproduce it in VSCode.

Are you experiencing the same issue as me?

**Comment by yaegassy** [comment] 2023-06-30 05:16
Yes. It reproduced. It also reproduces with another LSP client for Vim/Neovim, so perhaps it will reproduce with VSCode as well.

**Comment by chaozwn** [comment] 2023-06-30 05:19
> Yes. It reproduced. It also reproduces with another LSP client plugin for Vim/Neovim, so perhaps it will reproduce with VSCode as well.

i found it has the same issue in vscode too.
<img width="1162" alt="image" src="https://github.com/yaegassy/coc-volar/assets/51357674/787b9100-bb89-4d71-b876-b59669c76197">

**Comment by chaozwn** [comment] 2023-06-30 05:26
so, link volar issue: https://github.com/vuejs/language-tools/issues/3344

**Comment by yaegassy** [comment] 2024-03-10 04:12
I believe this problem has been resolved in version 2 of the language server. coc-volar has also changed its language server to version 2.

You are probably currently using Neovim's built-in lsp feature, but if a case arises where you need coc.nvim, try it.

**Closed by yaegassy** 2024-03-10 04:12 UTC
